
name: Publish Prereleases

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package -o build/"
      - name: Attach compilation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}-build-libs
          path: build/
          retention-days: 90
